### ISSUE TITLE
Incorrect PSI result

### ISSUE THREAD

**Issue by WoutDev** [jellevos/threshold-multiparty-psi#4]
I hope someone can shed some light on why this scenario does not work...

I've only changed the input data from the master branch to work with 4 clients and a server:

```c++
std::vector<long> client1_set({1, 2, 3, 4, 10, 11, 12, 13, 66, 14});
std::vector<long> client2_set({1, 2, 3, 4, 20, 21, 22, 66, 23, 24});
std::vector<long> client3_set({1, 2, 3, 4, 30, 31, 66, 32, 33, 34});
std::vector<long> client4_set({1, 2, 3, 4, 40, 66, 41, 42, 43, 44});
std::vector<long> server_set({1, 2, 3, 4, 5, 6, 7, 8, 9, 66});
```

And of course the call to `multiparty_psi`:
```c++
    std::vector<long> result = multiparty_psi(std::vector({client1_set, client2_set, client3_set, client4_set}), server_set,
                                              2,
                                              16, 4,
                                              keys);
```

The expected result would be { 1, 2, 3, 4, 66 } but I'm getting { 1, 2, 3, 4, 5, 9, 66 } instead...

Am I missing something? Should I be changing other parameters?

Thanks.

**Comment by jellevos** [comment]
The reason is that Bloom filters are approximate membership query structures, so the output will be a superset of the actual intersection. You can reduce the chance of these false positives occuring by choosing larger parameters for the number of bins $m$ and the number of hash functions $h$. In your example, they are set to $m = 16$ and $h = 4$. I have written some more about choosing these parameters in [a more recent paper](https://eprint.iacr.org/2022/721.pdf), see equation (19). You can iterate over increasing values of $h$ to find the minimum necessary value of $m$ for a maximum false positive rate $\varepsilon$. Also, the Rust implementation of that paper can be found [here](https://github.com/jellevos/private-logic-and-mpso/tree/master); it is a little bit easier to work with and it is significantly faster. I hope this helps!

**Comment by WoutDev** [comment]
Ah I was aware about the bloom filter properties but didn't knew it had an impact on such a small set. Thanks!
